Dataloader
sayakpaul/compressed-mirnet pull request #4
Opened 2022-08-29 15:35 UTC by soumik12345

2022-08-29 15:49 UTC, soumik12345 commented
https://github.com/sayakpaul/compressed-mirnet/issues/1

2022-08-30 03:00 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +class DatasetFactory(ABC):
Seems like the class already has methods implemented inside of it. I am not sure why it has the abstract method and why it's being subclasses from `ABC`. Help me understand why?

2022-08-30 03:01 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +    def load_data(self, low_light_image_path, enhanced_image_path):
`load_image` seems to be a better name. Also, do we want to crop validation images too?

2022-08-30 03:01 UTC, sayakpaul commented on compressed_mirnet/dataloader/commons.py
> +    image.set_shape([None, None, 3])
Why?

2022-08-30 03:03 UTC, sayakpaul commented on compressed_mirnet/dataloader/lol_dataloader.py
> +class LOLDataLoader(DatasetFactory):
Got it. If this is it, then I think it's okay to just add the methods to the factory class and not implement them.

2022-08-30 03:03 UTC, sayakpaul requested changes
Minor changes.

2022-08-30 06:20 UTC, soumik12345 commented on compressed_mirnet/dataloader/base.py
> +    def load_data(self, low_light_image_path, enhanced_image_path):
You're right, there's no point cropping validation images.

2022-08-30 06:21 UTC, soumik12345 commented on compressed_mirnet/dataloader/lol_dataloader.py
> +class LOLDataLoader(DatasetFactory):
Yes, I thought this would be a cleaner way to include more datasets.

2022-08-30 06:22 UTC, soumik12345 commented on compressed_mirnet/dataloader/base.py
> +class DatasetFactory(ABC):
https://github.com/sayakpaul/compressed-mirnet/pull/4#discussion_r957960501

2022-08-30 06:24 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +class DatasetFactory(ABC):
Yep, understood. Maybe delegate the implementations to the subclasses?

2022-08-30 06:32 UTC, soumik12345 commented on compressed_mirnet/dataloader/commons.py
> +    image.set_shape([None, None, 3])
It was unnecessary, I've removed it.

2022-08-30 06:33 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +class DatasetFactory(ABC):
@soumik12345 https://github.com/sayakpaul/compressed-mirnet/pull/4/files#r958052145

2022-08-30 06:34 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +        dataset = dataset.map(partial(self.load_image, apply_crop=apply_crop), num_parallel_calls=tf.data.AUTOTUNE)
Let's take the partial function in a separate line.

2022-08-30 06:35 UTC, sayakpaul requested changes
Just one major comment is on delegating the method implementations to the actual subclasses rather than in the factories.

2022-08-30 06:35 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +        return dataset
```suggestion
        return dataset.prefetch(tf.data.AUTOTUNE)
```

2022-08-30 07:01 UTC, sayakpaul requested changes
https://github.com/sayakpaul/compressed-mirnet/pull/4/files#r958052145

this is not yet addressed

2022-08-30 14:47 UTC, sayakpaul requested changes

2022-08-30 14:47 UTC, sayakpaul commented on compressed_mirnet/dataloader/base.py
> +        return low_light_image, enhanced_image
For the validation images, simply perform resizing?

2022-08-30 15:12 UTC, sayakpaul approved these changes

2022-08-30 15:13 UTC, merged